---
driver:
  name: ec2
  region: <%= ENV['AWS_REGION'] %>
  subnet_id: <%= ENV['SUBNET_ID'] %>
  security_group_ids: ["<%= ENV['SG_ID'] %>"]
  image_id: "<%= ENV['RHEL_AMI'] %>"
  instance_type: t2.medium
  aws_ssh_key_id: <%= ENV['SSH_KEY'] %>
  iam_profile_name: "S3_FullAccess"
  associate_public_ip: <%= ENV['PUBLIC_IP'] %>
  tags:
    Name: REAN-jenkins
    Owner: <%= ENV['TAGS_OWNER'] %>
    Environment: <%= ENV['TAGS_ENVIRONMENT'] %>
    Project: <%= ENV['TAGS_PROJECT'] %>
    Product: REAN-Jenkins

transport:
  ssh_key: <%= ENV['SSH_KEY_PATH'] %>
  connection_timeout: 10
  connection_retries: 5
  username: ec2-user
  # name: rsync

provisioner:
  name: chef_solo
  require_chef_omnibus: 13.9.4

platforms:
    - name: redhat-7
      block_device_mappings:
      - device_name: /dev/sdb
        ebs:
        volume_type: gp2
        virtual_name: test
        volume_size: 50
        delete_on_termination: true

suites:
  - name: jenkins-java-tar
    run_list:
      - recipe[REAN-jenkins::default]
    attributes:
      REAN-jenkins:
        devops_tools: true
        require_java: true
        require_service: true
        rhel_username: root
        rhel_password: root123
        admin_username: admin
        admin_password: admin123
        admin_fullname: administrator
        admin_email: <%= ENV['JENKINS_ADMIN_EMAIL'] %>
        terraform_s3_name: <%= ENV['S3_BUCKET'] %>
        terraform_s3_prefix: 'shared/platform-artifacts/terraform'
        terraform_s3_key: 'terraform_0.11.7_linux_amd64.zip'
        terraform_s3_region: <%= ENV['AWS_REGION'] %>
        terraform_checksum: '804d31cfa5fee5c2b1bff7816b64f0e26b1d766ac347c67091adccc2626e16f3'
        firewall: false
        selinux: true
        jenkins_plugin_online_install: true
    verifier:
      inspec_tests:
        - test/smoke
